### ISSUE TITLE
joycss命令行下功能不可用

### ISSUE THREAD

**Issue by yuanyan** [shepherdwind/joycss#10]
不应该执行到 graph\api.js 路径吧，php cgi？

```
C:\Users\Yuanyan\AppData\Roaming\npm\node_modules\joycss\src\spriteDef.js:275
    if (err) throw Error(data.toString());
                   ^
Error: CreateProcessW: 系统锟揭诧拷锟斤拷指锟斤拷锟斤拷锟侥硷拷锟斤拷

    at Error (unknown source)
    at SpriteDef.StdClass.extend._setDef (C:\Users\Yuanyan\AppData\Roaming\npm\n
ode_modules\joycss\src\spriteDef.js:275:20)
    at ChildProcess.cmdEnd (C:\Users\Yuanyan\AppData\Roaming\npm\node_modules\jo
ycss\src\graph\api.js:38:16)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at Process._handle.onexit (child_process.js:674:10)

F:\kuaipan\156197086\github\shepherdwind.github.com\demo\joycss\css>joycss -v
version 0.4.2
```

**Comment by shepherdwind** [comment]
joycss需要php命令(php cli)支持，这个我没有说明，在joycss.org文档中才提及。

api.js就是调用php命令去做拼图的工作，因为nodejs现在无法支持图片处理，所以现在拼图过程和图片大小计算过程还是通过php来执行的。

这部分api暂时独立出来，可以以后扩展出来，暂时没有很好的方法处理图片。因为在淘宝demo服务器是php的，所以暂时使用php来处理了。

**Comment by yuanyan** [comment]
node的处理图片的确很困扰，joycss挺赞的，但有个疑问，紧凑拼图目前来说是最优的实践，是什么原因使joycss也支持了水平或纵向拼图

**Comment by shepherdwind** [comment]
紧凑拼图有时候需要牺牲一些，比如需要多加一个标签，对于某些人来说，紧凑拼图是不可接受的，此外，还有水平平铺的，这个也和垂直水平平铺相关。

最初做的时候同时实现垂直水平平铺，不过后来觉得最优的方案应该是紧凑和垂直平铺结合使用。这样，即考虑到紧凑，同时可以自由按照自己想要的方式拼图。

两种方式结合，目的是让使用者尽量少约束，使用url参数也是基于同样的原因。

**Comment by cl412350533** [comment]
chenlong@ubuntu:~/Documents/joycss/css$ joycss -n test.css 
[config global]nochange for sprite image, use the backup url

/usr/local/lib/node_modules/joycss/src/spriteDef.js:392
    sprites['images'][imageInfo['file_location']] = mixin(imageInfo, {});
           ^
TypeError: Cannot read property 'images' of undefined
    at SpriteDef.StdClass.extend._setImageInfo (/usr/local/lib/node_modules/joycss/src/spriteDef.js:392:12)
    at StdClass.extend._setPos.layout (/usr/local/lib/node_modules/joycss/src/spriteDef.js:307:12)
    at Array.forEach (native)
    at forEach.utils.(anonymous function) (/usr/local/lib/node_modules/joycss/lib/utils.js:10:25)
    at SpriteDef.StdClass.extend._setPos (/usr/local/lib/node_modules/joycss/src/spriteDef.js:300:5)
    at SpriteDef.StdClass.extend._setDef (/usr/local/lib/node_modules/joycss/src/spriteDef.js:287:10)
    at ChildProcess.cmdEnd (/usr/local/lib/node_modules/joycss/src/graph/api.js:38:16)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at Process._handle.onexit (child_process.js:674:10)

这是什么情况，我用的ubuntu
node.js ,php cli，php GD库，pngquant, optipng都装了
这是什么问题阿

**Comment by shepherdwind** [comment]
这个，可以把你的test.css发给我看下不，发我邮箱，hanwen.sah@taobao.com。还有test.css引用的图片，一起打包发给我看看。

**Comment by cl412350533** [comment]
我的这个很简单。。
body{
    background:url(../images/bg.jpg?id=1&way=h) repeat-y 0 0;
    height:655px;
    width:964px;
}
就这么点东西。。

**Comment by shepherdwind** [comment]
哦，我知道原因了，id=1，这个在joycss里面，排序是从0开始的。默认的情况下，直接执行`joycss test.css`就可以了。joycss使用的是减法法则，默认所有图片都是需要拼图，默认放在一个sprite图里面，大部分图符合这样的规则，你不需要做任何处理，如果某个图不能加入sprite，或者一个默认的sprite不够，需要两个三个，然后再使用url参数。

你这里，直接使用了id=1，总共只有一张图，所有挂了，id=0的sprite没有图了。

还有，你使用的参数，joycss -n，这个是nochange模式，就是只修改css，图片使用上一次拼图结果——这说明，修改了css，但是没有涉及到图片的改动，所以只需要重新编译一下css，无需拼图。这是joycss特色之处。如果是第一次拼图，不能使用-n参数。

**Comment by shepherdwind** [comment]
另外，背景图中，way=h这样的参数，不再推荐使用了。现在joycss主要通过两种方式配置，命令行参数和背景图url参数，命令行参数，执行joycss -h可以看到所有参数。-h这样用于配置整张sprite布局的，使用joycss -x | -y | -c 三种配置(分别表示垂直，水平布局和紧凑拼图)，默认情况是自动布局模式。

**Comment by cl412350533** [comment]
原来是这样，安照你说的，修改之后就可以了。
刚刚接触joycss，好多东西都是从其他地方看来的，也不明太原理，得好好研究研究。
非常感谢！

**Comment by cl412350533** [comment]
我还想问一下，joycss是只能拼接本地的图片么，比如
.bg1{
    background:url(http://pet.wuhan.cc/html/UploadPic/2010/1/25/20101259479183.jpg) no-repeat;
    height:455px;
    width:464px;
}
.bg2{
    background:url(http://www.d.cn/upload/img/1104/20114191303183500792.JPEG) no-repeat;
    height:155px;
    width:164px;
}
这样的图片可以么？
我本地的执行结果：没有合并的图片，新生成的xxx.sprite.css也是按照原来的xxx.css文件照抄一边。
我看了一遍命令参数，貌似没发现有相关参数。

**Comment by shepherdwind** [comment]
是的，默认http图片不做拼图。https://github.com/shepherdwind/joycss/blob/master/src/spriteDef.js#L199 ，http图片比较麻烦，需要下载下来，所以不处理了。

   判断是否是需要做sprite的图片，默认情况下，所有的图片都需要做拼合处理，当遇
   到如下情况是，不做拼图：
1. 如果是http方式url，不做sprite
2. 图片url参数中有ESC_KEY，比如a.png?esc

在 2012-11-5，下午5:15，cl412350533 notifications@github.com 写道：

**Comment by cl412350533** [comment]
好的，谢谢了～

**Comment by senyawang** [comment]
我了遇到了这样的问题，不过我的css里用的是两组有id=0   也有id=1   不知道是什么原因？？？？？？？

**Comment by shepherdwind** [comment]
你加我旺旺，翰文，我看下。
