### ISSUE TITLE
添加对根目录的配置选项

### ISSUE THREAD

**Issue by deepure** [shepherdwind/joycss#15]
是否可以配置项目根目录，让joycss能正确读取到以绝对地址引用的图片
如

``` css
    background: url("/images/aaa.png") no-repeat;
```

**Comment by shepherdwind** [comment]
为什么需要使用绝对地址呢，现在路径读取都是依据css相对路径来的。绝对路径的情况倒是没有想过，如果有这样样的话，可以这么搞一下。
在 2013-3-5，下午3:51，deepure notifications@github.com 写道：

**Comment by deepure** [comment]
遗留问题吧，之前同事的习惯。

sass的配置项里也有相应的配置指定各资源文件路径，有了这个选项的话相对灵活些。
