### ISSUE TITLE
支持下sass吧

### ISSUE THREAD

**Issue by lorrylockie** [shepherdwind/joycss#17]
支持下sass吧
强烈需求

**Comment by shepherdwind** [comment]
如果这个库好用的话，应该可以，你试下[node-sass](https://github.com/andrew/node-sass)是否可以兼容你现在的使用吧。如果可以，我就加上去。

**Comment by lorrylockie** [comment]
库是好用的，我正在项目中使用，主要是nodejs方面，方便前端集成
node-sass应该可以，大概看了下他的文档

要不尝试下？

**Comment by shepherdwind** [comment]
sass支持加上了，把css源读取的功能独立出来，在src/cssSource.js里面，你看下好用不，有问题继续提issue哈。那个-s的还是不用比较好，我不喜欢那个功能。

**Comment by shepherdwind** [comment]
忘了提醒一下，node-sass模块需要自行安装，我看那个库有点大，sass和less都不是joycss必须依赖的库，大家按需安装就好。
