### ISSUE TITLE
source 参数不符合预期

### ISSUE THREAD

**Issue by lorrylockie** [shepherdwind/joycss#18]
在当前目录下，有个index.source.css
执行命令 joycss  index.css -s    //控制台出现命令 help 提示

 执行 joycss index.source.css -s //生成了 index.source.source.css 

是我理解错误了吗

**Comment by shepherdwind** [comment]
这个是这样的， joycss a.css，或copy a.css到a.source.css，如果命令行中有参数-s，会首先查找文件名对应的.source文件。也就是生成的文件是a.css，源文件是.source.css，如果第一次没有读取到.source.css会生成一份。

那个sass的功能，我周末加上吧，呵呵，我现在主要用less来作为输入源，有两个css文件始终是麻烦。
