### ISSUE TITLE
joycss 作为node模块使用，希望提供更加友好的文档和api

### ISSUE THREAD

**Issue by lorrylockie** [shepherdwind/joycss#22]
### 目前使用上的几个问题
1.  文档较少，理解起来有困难
2.  new Joycss(a,b,c) 。  根据私下沟通，了解到
   
    1).  其中a必须是绝对路径
   
    2).  如果c提供的话，那么c中背景图的路径是相对a的filename当前路径的
   
   以上两条文档确实
3.  期望 2 能有所改进，支持相对路径。

**Comment by lorrylockie** [comment]
补充一点：
再将joycss集成到grunt中的时候，出现了问题，同样的代码，以单独的node模块执行没有问题，以grunt任务的形式执行有问题

``` javascript
var Joycss = require('joycss');
var res = new Joycss("D:\\pratise\\grunt-joycss\\test\\src\\a.css");
```

在grunt中没有任何执行结果，疑惑

**Comment by shepherdwind** [comment]
现在大致是这样的，joycss支持两种输入类型，文件路径或者cssText，文件路径的方式，那么文件路径必须是绝对路径，这个就和node的file system是一致，如果我在joycss的目录去执行fs.readFileSync的话，肯定是错误的，作为node模块写，必须输入绝对路径，这个在完成也挺容易的。

``` js
var filename = path.join(__dirname, file);
```

三个参数中，第一个参数是必须的，不过是文件路径还是cssText方式，都必须输入文件路径，第一个参数，filename，如果没有第三个参数输入cssText，那么第一个参数filename就是文件路径。除了处理输入，joycss还得处理输出地址，现在的情况是根据第一个参数来做的。

文件保存规则，比如filename是/path/to/a.css

在默认情况下，输出的是/path/to/a.sprite.css ，如果有第三个参数，那么filename就是保存的文件地址，所以joycss有管道输入的用法

```
lessc a.less | joycss -p a.css
```

那个第二个问题，不执行的情况我再测试一下吧。

> 期望 2 能有所改进，支持相对路径。

这个我不是很明白，是第一个参数filename支持相对路径吗？

**Comment by lorrylockie** [comment]
第一个问题这么说，清楚多了。
先确定第二个问题吧，第三个问题我也在想下，之前没怎么想明白
