### ISSUE TITLE
mac 下无法安装

### ISSUE THREAD

**Issue by xunuo** [shepherdwind/joycss#23]
npm install node-gd  

安装时候报错，以下是片段

```
npm ERR! node-gd@0.2.2 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the node-gd@0.2.2 install script.
npm ERR! This is most likely a problem with the node-gd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-gd
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.3.0

```

**Comment by shepherdwind** [comment]
安装node-gd稍微有些麻烦，默认mac可以使用php cli就可以吧。安装gd需要首先brew install gd 

snow notifications@github.com编写：

**Comment by shepherdwind** [comment]
``` sh
brew install gd
npm install node-gyp -g
npm install -g node-gd
```

需要这样安装。

**Comment by xunuo** [comment]
感谢 但是 brew: command not found 这个要另外装么

**Comment by xunuo** [comment]
哦，谢谢，我自己了解了一下 找到相关文章了：
http://www.cppblog.com/kongque/archive/2011/09/23/156624.html

用这条就ok了
curl -LsSf http://github.com/mxcl/homebrew/tarball/master | sudo tar xvz -C/usr/local --strip 1

**Comment by shepherdwind** [comment]
呵呵，brew与mac的关系就像，apt-get之于ubunuu，npm之于nodejs。不过如果你没装，需要注意，很多brew安装的模块，都需要源码编译，比如gd就是这样，需要gcc，这个你得安装xcode的cli模块。

上面的过程稍微有些复杂，不过，作为开发者，是必须有的。

snow notifications@github.com编写：

**Comment by xunuo** [comment]
了解了，非常感谢！
