### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by RenShine** [shepherdwind/joycss#25]
![image](https://cloud.githubusercontent.com/assets/6385962/2752204/0e4f079e-c903-11e3-978f-91964ef234d7.png)

不知道是什么原因

**Comment by shepherdwind** [comment]
好像是因为php的报错，你把完整的错误信息贴上来看看

**Comment by RenShine** [comment]
![image](https://cloud.githubusercontent.com/assets/6385962/2752411/753f34ea-c90a-11e3-865b-ca24a93bfaee.png)
完整的报错信息是这样的    我的path里面是有PHP的   Phoinfo输出的信息也有gd库

**Comment by shepherdwind** [comment]
这个应该是php cli有什么模块加载失败，你直接运行php --info或者，php --version，看看报什么错误。

这里有一篇文档，你看下https://github.com/shepherdwind/joycss/wiki/how-to-install

**Comment by RenShine** [comment]
成功运行起joycss  非常好用   谢谢作者细心解答   我的Php少了Mongo模块
