### ISSUE TITLE
CentOS上执行joycss失败，报Error: spawn ENOENT

### ISSUE THREAD

**Issue by shuizhongyueming** [shepherdwind/joycss#33]
我的系统是centos，安装了pngquant，joycss的版本号是0.5.1。但是运行joycss的时候，总是失败，报`spawn ENOENT`错误。上网查了下这个错误具体表示的意义：

> `Fatal error: spawn ENOENT` means when trying to spawn a process, it failed because the command does not exist. Likely due to a missing dependency. 

但是还是不太明白，也没有任何头绪，以下是具体的错误信息，希望能指点一下具体出错的地方，谢谢了。

```
[wangxing@Ct-OS65 css]$ joycss play.min.css 
[option]use layout auto
[Success] 1 images will merge to one image play.min-sprite.png[293x298]


events.js:77
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at exports._errnoException (util.js:671:11)
    at Process.ChildProcess._handle.onexit (child_process.js:776:32)
```

**Comment by shepherdwind** [comment]
你安装最新的0.6试试看看

**Comment by shuizhongyueming** [comment]
已经升级到0.6.1了，现在单纯使用joycss，是可以运行成功的。但是，如果使用grunt-joycss的话，还是会报同样的错误...

**Comment by shepherdwind** [comment]
grunt我倒是没有更新，接口变量，明天我改下。grunt那个还是老版的joycss

**Comment by shepherdwind** [comment]
grunt-joycss发布0.2版本，你试用下看看

**Comment by shuizhongyueming** [comment]
还是之前的系统环境，现在joycss是0.6.1的版本，但是执行图片合并的时候，?esc的参数失效了，只有远程路径的图片才不会合并

而且有个很诡异的问题：看到git里面有0.6.4的版本，调用npm install joycss@0.6.4去安装这个版本的，可是最终调用joycss --version 出来的却是0.6.1

```
joycss@0.6.4 /usr/lib/node_modules/joycss
├── co@3.1.0
├── unyield@0.0.1
├── thunkify@2.1.2
├── co-exec@1.1.0
├── osenv@0.0.3
├── image-size@0.3.5
├── shelljs@0.1.4
├── debug@2.1.0 (ms@0.6.2)
├── commander@1.1.1 (keypress@0.1.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── co-fs@1.2.0 (thunkify@0.0.1, co-from-stream@0.0.0)
├── css@2.1.0 (inherits@2.0.1, urix@0.1.0, source-map@0.1.40, source-map-resolve@0.3.1)
├── less@1.7.5 (graceful-fs@3.0.4, mime@1.2.11, clean-css@2.2.16, source-map@0.1.40, request@2.40.0)
└── gnode@0.1.0 (regenerator@0.6.8)
[wangxing@Ct-OS65 css]$ joycss --version
0.6.1
```

查看package.json里面看到的也是0.6.4

**Comment by shepherdwind** [comment]
这是个bug，以前没有测试用例，有些问题，今天加一下。

**Comment by shepherdwind** [comment]
`esc`支持了，可以看这个[用例](https://github.com/shepherdwind/joycss/commit/fbe8609702f563e783923bd7483e4fde75baaf3a#diff-47f346da1e835b9bcfbf582e4071d3afR18)。那个版本的问题，你可以直接运行`joycss`，会返回完整的路径，可以看下源码，我这边显示还是正常的。
